---
title: "Day 3 - Assessing Causal Evidence"
#author: "JP"
#date: "January 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Morning

[Lecture Slides](https://jonnyphillips.github.io/Causal_Critiques/Day 3/Slides_Day_3_v2.pdf)

## Afternoon - Practicing Critiques

For each of the papers below:

(a) Complete the [Paper Summary Template](https://jonnyphillips.github.io/Causal_Critiques/Day 1/Paper_summary_template.pdf) from Day 1;
(b) Write a critique of the causal methodology, highlighting the assumptions that are made and whether there is any evidence they are met. 
(c) Explain what alternative explanations might also be consistent with the research findings.
(d) Conclude by summarising how much you believe the findings of the paper.

1. [Acemoglu et al 2001](https://jonnyphillips.github.io/Causal_Critiques/Day 4/Papers for Critique/AJR 2001.pdf)
2. [De La O 2013](https://jonnyphillips.github.io/Causal_Critiques/Day 4/Papers for Critique/De_la_O_Do.pdf)
3. [Olken 2009](https://jonnyphillips.github.io/Causal_Critiques/Day 4/Papers for Critique/Olken TV and Social Capital.pdf)

## Afternoon - Critiquing the Data

To overcome the causal problems we saw yesterday, Titiunik implements a regression discontinuity. 

1. Implement the regression discontinuity using your measure of 'close elections', your indicator of incumbency status and your measure of electoral performance in 2004.

2. Interpret the findings of the regression discontinuity. How do they differ from the observational results in Day 2?

3. One assumption of our regression discontinuity is that comparing incumbents that just won and lost elections in 2000 will produce 'balance' on potential omitted variables. There are thousands of variables we could check, but let's assess balance on the size of the municipality by comparing the number of voters in 2000 within 5\% of a tied election.

4. How does the balance close to the threshold compare with the balance of winners and losers in the full dataset?

5. Another assumption of regression discontinuity is continuity in the distribution of the variable measuring distance to the threshold. Test this assumption by implementing a McCrary density test. What do the results show?

